# Generated by Django 4.2.5 on 2023-09-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='person',
            name='track',
        ),
    ]
